# Generated by Django 4.2.2 on 2023-06-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_store_custo_last_na_2e448d_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='promotions',
            new_name='promotion',
        ),
    ]
