# Generated by Django 4.2.2 on 2023-06-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_promotions_product_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='promotion',
            new_name='promotions',
        ),
    ]
