# Generated by Django 4.2.2 on 2023-06-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_collection_alter_product_promotions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collection',
            new_name='collections',
        ),
    ]
