# Generated by Django 4.2.2 on 2023-06-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_collection_product_collections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collections',
            new_name='collection',
        ),
    ]
