# Generated by Django 4.2.2 on 2023-06-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_collections_product_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
