# Generated by Django 4.2.2 on 2023-07-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
