# Generated by Django 4.2.2 on 2023-06-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_taggeditem_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taggeditem',
            managers=[
            ],
        ),
    ]
